from __future__ import annotations

import base64
import json
import mimetypes
import os
import time
import urllib.error
import urllib.request
from pathlib import Path

from ...models import VideoRenderRequest, VideoRenderResult
from ...utils import ensure_dir, retry_call, run_command
from .base import BaseVideoProvider

# Prepended to scene text when topic.content_angle == "funny_cartoon" (Runway image-to-video).
# Tuned toward premium vertical 3D CGI shorts (Pixar/Disney-style), not Ken Burns on stills.
_FUNNY_CARTOON_RUNWAY_PREFIX = (
    "Premium 3D CGI animated short, theatrical feature quality: rounded appealing characters, saturated "
    "colors, soft cinematic sunlight, shallow depth of field. Full-body animation—running, walking, head turns, "
    "expressive faces; hair/clothes secondary motion; props and crowds move subtly. Continuous 3D motion—not "
    "a static frame or slideshow. Camera: dynamic follow, dolly, or light handheld energy. Playful comedy timing. "
)


class RunwayVideoProvider(BaseVideoProvider):
    name = "runway"

    def __init__(self) -> None:
        self.api_key = os.environ.get("RUNWAY_API_KEY", os.environ.get("RUNWAYML_API_SECRET", "")).strip()
        self.model = os.environ.get("RUNWAY_MODEL", "gen4.5").strip()
        self.api_version = os.environ.get("RUNWAY_API_VERSION", "2024-11-06").strip()
        self.ratio = os.environ.get("RUNWAY_RATIO", "720:1280").strip()
        self.timeout_seconds = int(os.environ.get("RUNWAY_TASK_TIMEOUT_SECONDS", "900").strip() or "900")
        self.poll_interval_seconds = int(os.environ.get("RUNWAY_POLL_INTERVAL_SECONDS", "5").strip() or "5")

    def available(self) -> bool:
        return bool(self.api_key)

    def render(self, request: VideoRenderRequest) -> VideoRenderResult:
        ffmpeg_bin = os.environ.get("FFMPEG_BIN", "ffmpeg")
        work_dir = ensure_dir(request.output_dir / "_runway")
        generated_clips: list[Path] = []
        notes: list[str] = []

        scene_seed_images = [Path(path) for path in request.scene_image_paths if Path(path).exists()]
        character_seed_images = [Path(path) for path in request.character_sheet_image_paths if Path(path).exists()]
        thumbnail_seed = Path(request.thumbnail.thumbnail_path) if request.thumbnail.thumbnail_path else None
        if thumbnail_seed and not thumbnail_seed.exists():
            thumbnail_seed = None

        funny_cartoon = getattr(request.topic, "content_angle", None) == "funny_cartoon"
        if funny_cartoon:
            notes.append("Runway prompt: funny_cartoon motion prefix applied to each scene.")

        for scene in request.script.scenes:
            seed_image = self._pick_seed_image(scene.index, scene_seed_images, character_seed_images, thumbnail_seed, work_dir, request)
            prompt_text = self._runway_prompt_text(request, scene)
            task_id = self._create_image_to_video_task(
                prompt_image=self._to_data_uri(seed_image),
                prompt_text=prompt_text,
                duration=self._scene_duration(scene.duration_seconds),
            )
            task = self._wait_for_task(task_id)
            output_urls = task.get("output") or []
            if not output_urls:
                raise RuntimeError(f"Runway task {task_id} completed without output URLs.")
            clip_path = work_dir / f"scene_{scene.index:02d}.mp4"
            self._download_file(str(output_urls[0]), clip_path)
            generated_clips.append(clip_path)
            notes.append(f"Scene {scene.index} generated by Runway task {task_id}.")

        concat_file = work_dir / "concat.txt"
        concat_file.write_text("\n".join(f"file '{path.name}'" for path in generated_clips), encoding="utf-8")
        stitched_path = work_dir / "stitched.mp4"
        run_command(
            [
                ffmpeg_bin,
                "-y",
                "-f",
                "concat",
                "-safe",
                "0",
                "-i",
                str(concat_file),
                "-c",
                "copy",
                str(stitched_path),
            ],
            cwd=work_dir,
        )

        final_command = [ffmpeg_bin, "-y", "-i", str(stitched_path)]
        if request.include_voiceover and request.voiceover_audio_path and request.voiceover_audio_path.exists():
            final_command.extend(["-i", str(request.voiceover_audio_path)])
        final_command.extend(["-c:v", "libx264", "-preset", "medium", "-pix_fmt", "yuv420p"])
        if request.include_voiceover and request.voiceover_audio_path and request.voiceover_audio_path.exists():
            final_command.extend(["-c:a", "aac", "-b:a", "192k", "-shortest"])
        else:
            final_command.extend(["-an"])
        final_command.append(str(request.final_output_path))
        run_command(final_command)

        return VideoRenderResult(
            provider_name=self.name,
            output_path=str(request.final_output_path),
            status="rendered",
            notes=notes,
        )

    def validate_access(self) -> dict[str, str]:
        if not self.available():
            raise RuntimeError("RUNWAY_API_KEY is not configured.")
        return {"provider": self.name, "status": "configured", "model": self.model}

    def _runway_prompt_text(self, request: VideoRenderRequest, scene) -> str:
        base = (scene.animation_prompt or scene.visual_prompt or scene.narration or "").strip()
        if getattr(request.topic, "content_angle", None) == "funny_cartoon":
            prefix = _FUNNY_CARTOON_RUNWAY_PREFIX
            room = max(0, 1000 - len(prefix))
            return (prefix + base[:room])[:1000]
        return base[:1000]

    def _request(self, method: str, path: str, body: dict | None = None) -> dict:
        data = json.dumps(body).encode("utf-8") if body is not None else None
        request = urllib.request.Request(
            f"https://api.dev.runwayml.com{path}",
            data=data,
            headers={
                "Authorization": f"Bearer {self.api_key}",
                "Content-Type": "application/json",
                "X-Runway-Version": self.api_version,
            },
            method=method,
        )

        def _do_request() -> dict:
            try:
                with urllib.request.urlopen(request, timeout=90) as response:
                    raw = response.read()
            except urllib.error.HTTPError as exc:
                error_body = exc.read().decode("utf-8", errors="replace")
                raise RuntimeError(f"Runway API error {exc.code}: {error_body}") from exc
            except urllib.error.URLError as exc:
                raise RuntimeError(f"Runway API request failed: {exc}") from exc
            if not raw:
                return {}
            return json.loads(raw.decode("utf-8"))

        return retry_call(_do_request, attempts=2, delay_seconds=1.0, backoff=2.0)

    def _create_image_to_video_task(self, *, prompt_image: str, prompt_text: str, duration: int) -> str:
        payload = {
            "model": self.model,
            "promptImage": prompt_image,
            "promptText": prompt_text,
            "ratio": self.ratio,
            "duration": duration,
        }
        response = self._request("POST", "/v1/image_to_video", payload)
        task_id = response.get("id")
        if not task_id:
            raise RuntimeError(f"Runway did not return a task id: {response}")
        return str(task_id)

    def _wait_for_task(self, task_id: str) -> dict:
        deadline = time.time() + self.timeout_seconds
        while time.time() < deadline:
            task = self._request("GET", f"/v1/tasks/{task_id}")
            status = str(task.get("status", "")).upper()
            if status in {"SUCCEEDED", "COMPLETED"}:
                return task
            if status in {"FAILED", "CANCELED", "CANCELLED", "ABORTED"}:
                raise RuntimeError(f"Runway task {task_id} ended with status {status}: {task}")
            time.sleep(self.poll_interval_seconds)
        raise TimeoutError(f"Runway task {task_id} did not complete within {self.timeout_seconds} seconds.")

    def _download_file(self, url: str, output_path: Path) -> Path:
        request = urllib.request.Request(url, method="GET")

        def _do_download() -> bytes:
            try:
                with urllib.request.urlopen(request, timeout=180) as response:
                    return response.read()
            except urllib.error.HTTPError as exc:
                error_body = exc.read().decode("utf-8", errors="replace")
                raise RuntimeError(f"Runway output download error {exc.code}: {error_body}") from exc
            except urllib.error.URLError as exc:
                raise RuntimeError(f"Runway output download failed: {exc}") from exc

        output_path.write_bytes(retry_call(_do_download, attempts=2, delay_seconds=1.0, backoff=2.0))
        return output_path

    def _pick_seed_image(
        self,
        scene_index: int,
        scene_images: list[Path],
        character_images: list[Path],
        thumbnail_image: Path | None,
        work_dir: Path,
        request: VideoRenderRequest,
    ) -> Path:
        if len(scene_images) >= scene_index:
            return scene_images[scene_index - 1]
        if character_images:
            return character_images[(scene_index - 1) % len(character_images)]
        if thumbnail_image:
            return thumbnail_image
        return self._create_placeholder_seed(scene_index=scene_index, work_dir=work_dir, request=request)

    def _create_placeholder_seed(self, *, scene_index: int, work_dir: Path, request: VideoRenderRequest) -> Path:
        output_path = work_dir / f"seed_{scene_index:02d}.png"
        if output_path.exists():
            return output_path

        ffmpeg_bin = os.environ.get("FFMPEG_BIN", "ffmpeg")
        filter_graph = ",".join(
            [
                "format=rgb24",
                "drawbox=x=0:y=0:w=720:h=1280:color=0x0f172a:t=fill",
                "drawbox=x=40:y=80:w=640:h=1120:color=0x1d4ed8@0.22:t=fill",
                "drawbox=x=110:y=170:w=500:h=940:color=0xf97316@0.16:t=fill",
                "drawbox=x=170:y=260:w=380:h=760:color=0x22c55e@0.12:t=fill",
                "drawbox=x=210:y=300:w=300:h=300:color=white@0.14:t=fill",
                "drawbox=x=250:y=640:w=220:h=420:color=white@0.10:t=fill",
                "gblur=sigma=0.7",
            ]
        )
        run_command(
            [
                ffmpeg_bin,
                "-y",
                "-f",
                "lavfi",
                "-i",
                "color=c=0x0f172a:s=720x1280:d=1",
                "-frames:v",
                "1",
                "-vf",
                filter_graph,
                str(output_path),
            ]
        )
        return output_path

    def _to_data_uri(self, image_path: Path) -> str:
        mime_type = mimetypes.guess_type(str(image_path))[0] or "image/png"
        image_bytes = image_path.read_bytes()
        encoded = base64.b64encode(image_bytes).decode("utf-8")
        return f"data:{mime_type};base64,{encoded}"

    def _scene_duration(self, duration_seconds: float) -> int:
        rounded = int(round(duration_seconds))
        if rounded <= 7:
            return 5
        return 10
